# Generated by Django 5.2.7 on 2025-11-04 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0005_signal_atr_at_entry_signal_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_global', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroupAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.asset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.assetgroup')),
            ],
            options={
                'unique_together': {('group', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='assets',
            field=models.ManyToManyField(related_name='groups', through='portfolios.AssetGroupAsset', to='market_data.asset'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('initial_capital', models.FloatField(default=100000.0)),
                ('risk_per_trade', models.FloatField(default=0.01)),
                ('rebalance', models.CharField(choices=[('NONE', 'No rebalance'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='NONE', max_length=16)),
                ('max_total_positions', models.PositiveIntegerField(default=0, help_text='0 = illimité (MVP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.5)),
                ('max_positions', models.PositiveIntegerField(default=3)),
                ('per_trade_risk', models.FloatField(blank=True, help_text='Override risk_per_trade du portefeuille', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolios.assetgroup')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolios.portfolio')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_allocations', to='strategies.strategy')),
            ],
            options={
                'ordering': ['portfolio', '-weight'],
                'unique_together': {('portfolio', 'strategy', 'group')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capital_start', models.FloatField(default=0.0)),
                ('equity_final', models.FloatField(default=0.0)),
                ('n_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_R', models.FloatField(default=0.0)),
                ('expectancy_R', models.FloatField(default=0.0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('entry_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('qty', models.PositiveIntegerField()),
                ('stop_price', models.FloatField(blank=True, null=True)),
                ('exit_date', models.DateField()),
                ('exit_price', models.FloatField()),
                ('outcome', models.CharField(default='EOD', max_length=32)),
                ('r_multiple', models.FloatField(default=0.0)),
                ('pnl', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.portfolioallocation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolios.portfoliorun')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategy')),
            ],
            options={
                'ordering': ['entry_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assetgroup',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='PortfolioEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equity', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_points', to='portfolios.portfoliorun')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('run', 'date')},
            },
        ),
    ]
