# Generated by Django 5.2.7 on 2025-11-04 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0005_signal_atr_at_entry_signal_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=8)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('entry_price', models.FloatField()),
                ('stop_init', models.FloatField()),
                ('stop_cur', models.FloatField()),
                ('take_profits', models.JSONField(blank=True, default=list)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('MANUAL', 'Manual'), ('EOD', 'End of period'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('r_multiple', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='portfolios.portfolioallocation')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market_data.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolios.portfolio')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='strategies.signal')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('MOVE_SL', 'Move SL'), ('ADD_TP', 'Add TP'), ('PARTIAL_EXIT', 'Partial exit'), ('CLOSE', 'Close'), ('NOTE', 'Note')], max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portfolios.position')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
