# Generated by Django 5.2.7 on 2025-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_position_positionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='guardrails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='position',
            name='risk_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='risk_per_share',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='sl_method',
            field=models.CharField(blank=True, default='PERCENT', max_length=16),
        ),
        migrations.AddField(
            model_name='position',
            name='trailing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
