# Generated by Django 5.2.7 on 2025-11-03 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CUSTOM', 'Code personnalisé'), ('RS', 'Relative Strength'), ('VCP', 'Volatility Contraction'), ('PP', 'Pocket Pivot'), ('SMD', 'Smart Money Divergence')], max_length=10)),
                ('code', models.TextField(blank=True, help_text='Code Python pour stratégie custom')),
                ('parameters', models.JSONField(default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('strength', models.CharField(choices=[('WEAK', 'Faible'), ('MEDIUM', 'Moyen'), ('STRONG', 'Fort')], max_length=10)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market_data.asset')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-date', '-score'],
                'unique_together': {('strategy', 'asset', 'date')},
            },
        ),
    ]
