# Generated by Django 5.2.7 on 2025-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
