# Generated by Django 5.2.7 on 2025-11-03 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0002_alter_signal_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_memory_mb',
            field=models.PositiveIntegerField(default=256),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_runtime_ms',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='strategy',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='code',
            field=models.TextField(blank=True, help_text='Fonction evaluate(df_prices, df_indicators, params) -> dict'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['strategy', 'asset', 'date'], name='strategies__strateg_4bbb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['asset', '-date'], name='strategies__asset_i_28c451_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['is_active', 'type'], name='strategies__is_acti_baf9a2_idx'),
        ),
    ]
