# Generated by Django 5.2.7 on 2025-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_description_strategy_last_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(choices=[('CUSTOM', 'Code personnalisé'), ('RS', 'Relative Strength'), ('VCP', 'Volatility Contraction'), ('PP', 'Pocket Pivot'), ('SMD', 'Smart Money Divergence'), ('GC', 'Golden Cross'), ('VB', 'Volume Breakout')], max_length=10),
        ),
    ]
