# Generated by Django 5.2.7 on 2025-11-03 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0004_alter_strategy_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='atr_at_entry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='direction',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5),
        ),
        migrations.AddField(
            model_name='signal',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='rr_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='stop_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='take_profits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='signal',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('entry_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('stop_price', models.FloatField()),
                ('take_profits', models.JSONField(blank=True, default=list)),
                ('qty', models.FloatField(default=0.0)),
                ('fees', models.FloatField(default=0.0)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=16)),
                ('r_multiple', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.asset')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.signal')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
