# Generated by Django 5.2.7 on 2025-10-14 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('equity', 'Equity'), ('index', 'Index'), ('fx', 'Forex')], max_length=12)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('y_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('av_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('yahoo', 'Yahoo'), ('alphavantage', 'AlphaVantage')], max_length=16)),
                ('timeframe', models.CharField(choices=[('1D', 'Daily'), ('1W', 'Weekly')], max_length=2)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bars_1D', 'Bars 1D'), ('bars_1W', 'Bars 1W')], max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='market_data.asset')),
            ],
            options={
                'unique_together': {('asset', 'kind')},
            },
        ),
    ]
