# Generated by Django 5.2.7 on 2025-11-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sma_20', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('sma_200', models.FloatField(blank=True, null=True)),
                ('ema_12', models.FloatField(blank=True, null=True)),
                ('ema_26', models.FloatField(blank=True, null=True)),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_hist', models.FloatField(blank=True, null=True)),
                ('bb_upper', models.FloatField(blank=True, null=True)),
                ('bb_middle', models.FloatField(blank=True, null=True)),
                ('bb_lower', models.FloatField(blank=True, null=True)),
                ('atr_14', models.FloatField(blank=True, null=True)),
                ('volume_sma_20', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market_data.asset')),
            ],
            options={
                'ordering': ['asset', '-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
