# Generated by Django 5.2.7 on 2025-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['asset', 'date'], name='indicators__asset_i_7b63df_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['-date'], name='indicators__date_f996b1_idx'),
        ),
    ]
