# Generated by Django 5.2.7 on 2025-11-07 08:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NSDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('x_window', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('y_resolution', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(50)])),
                ('horizon_bars', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('tp_margins', models.JSONField(default=list, help_text='Liste de marges TP (ex: [0.10, 0.15])')),
                ('use_ma', models.BooleanField(default=True)),
                ('ma_periods', models.JSONField(default=list, help_text='Ex: [20, 50]')),
                ('use_bb', models.BooleanField(default=True)),
                ('bb_period', models.PositiveIntegerField(default=20)),
                ('bb_k', models.FloatField(default=2.0)),
                ('use_atr', models.BooleanField(default=True)),
                ('atr_period', models.PositiveIntegerField(default=14)),
                ('scaling_mode', models.CharField(choices=[('grid_scaled', 'Grid scaled (position 0..Y selon min/max de ref + indicateurs)'), ('relative_feats', "Relative features (ratios invariants d'échelle)")], default='grid_scaled', max_length=32)),
                ('labels_path', models.CharField(blank=True, default='', max_length=255)),
                ('dataset_path', models.CharField(blank=True, default='', max_length=255)),
                ('manifest_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('timeframe', models.CharField(default='1D', max_length=16)),
                ('asset_class', models.CharField(default='equities', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('labels', 'Build Labels'), ('dataset', 'Build Dataset'), ('backtest', 'Backtest/Validation'), ('train', 'Train (ML)')], max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('log', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='neuronal_strategy.nsdataset')),
            ],
        ),
        migrations.AddField(
            model_name='nsdataset',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='neuronal_strategy.nsuniverse'),
        ),
        migrations.CreateModel(
            name='NSPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('ts', models.DateTimeField()),
                ('prob_tp10', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prob_tp15', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('decision', models.BooleanField(default=False)),
                ('label_tp10', models.BooleanField(blank=True, null=True)),
                ('label_tp15', models.BooleanField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='neuronal_strategy.nsdataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'instrument', 'ts'], name='neuronal_st_dataset_e9d440_idx')],
                'unique_together': {('dataset', 'instrument', 'ts')},
            },
        ),
    ]
