# Generated by Django 5.2.7 on 2025-11-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronal_strategy', '0001_initial'),
        ('portfolios', '0003_position_guardrails_position_risk_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsuniverse',
            name='asset_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ns_universes', to='portfolios.assetgroup'),
        ),
        migrations.AddField(
            model_name='nsuniverse',
            name='asset_group_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
