# Generated by Django 5.2.7 on 2025-11-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronal_strategy', '0002_nsuniverse_asset_group_nsuniverse_asset_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsdataset',
            name='timeframe',
            field=models.CharField(choices=[('1D', 'Daily'), ('1H', 'Hourly')], default='1D', max_length=2),
        ),
    ]
